### ISSUE TITLE
Issue with credit detection

### ISSUE THREAD

**Issue by flopon** [pabloromeo/clusterplex#231]
End credit detection is offered by plex server since 1.31.0.

There is definitely a lot to fix on PLEX team side (forum is full of bug reports), but I think there is also an issue specifically when using clusterplex, as I have been able to use it when disactivating the docker mod, but was not able to use it whit docker mod enabled (log showing a "Job failed: Decryption failed" error in this case.

Is someone been able to use PLEX credit detection while using clusterplex ?

**Comment by pabloromeo** [comment]
Yeah, I think you may be right. Just tested it and I've found an issue related to credit detection, which causes the worker to fail.
However, I'm not entirely sure the "Decryption failed" error is caused by us, that seems to happen either way, from what I saw on the forum issues.
I'll let you know once I have a fix ready so you can try it out.

**Comment by pabloromeo** [comment]
Release v1.4.5 https://github.com/pabloromeo/clusterplex/releases/tag/v1.4.5 should fix the Credits Detection issue

**Comment by flopon** [comment]
Nop, still having the same issue, with a `[Req#3d5/CreditsDetectionManager] Job failed: Decryption failed` error, not present in the log if I remove the docker mod.

The file is readen on local server, but the credit detection fail.
Seems to be trickier than just on ly having to read the file locally !

I will try to do some more analysis the next week.

**Comment by pabloromeo** [comment]
That's odd! Yeah, ultimately what I was seeing is that Plex's Credits Detection was also calling the transcoder (which we overwrite), however, for Credits Detection they don't respect their own configured `transcode` path, and instead use `/tmp` directly. Using `/tmp` fails with ClusterPlex since it's not shared across workers.
Ultimately what I did was bypass any sort of remote transcoding for Credit Detection, just calling Plex's local transcoder directly.

Regarding the error message, yes, I see that too in the logs, but given that in the forum there are tons of messages about that error and a reply from a Plex developer addressing it, I didn't pay much attention, especially since credit detection started working after the 1.4.5 fix.

**Comment by flopon** [comment]
Haven't a lot of time to investigate since my original post, but FYI, still thinking there is an issue in `transcoder.js`.

If I just replace the modified `Plex Transcoder` with the original one, credit detection is perfectly working (and of course distributed transcoding did not ^^)

Will try to investigated further.

PS : I'm on the Dockermod Version, in a LXC unprivileged CT, on Proxmox 8.0

**Comment by flopon** [comment]
Hi, quick update on this (very) old issue: I finally found some time to isolate the root cause.

PlexCreditsDetection uses the Plex Transcoder stdout as a data stream. At the same time, ClusterPlex also writes diagnostic messages to stdout (console.log, wrapper/sentinel echo, death({ debug: true })), which corrupts the stream and leads to the well-known Decryption failed error.

Keeping ClusterPlex diagnostics off stdout during CreditsDetection fixes the issue while preserving the existing local transcode flow.

I also tested removing the forced-local path. Distributed credits would still need some additional work because Plex creates temporary files under /run/plex-temp/, so that workspace would need to be shared between PMS and the workers. On top of that, the worker's stdout is not relayed back to the PMS process, which appears to be required for the credits detection workflow.

So the immediate fix seems to be: keep CreditsDetection local, but keep its stdout path clean. Distributed CreditsDetection would require a bit more work.
